language: ruby
rvm:
- 2.1.2
before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database dynamicmodel_test;'
- bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare --trace
script:
- RAILS_ENV=test bundle exec rake spec
