production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  host: localhost
  database: dynamicmodel_prod
  username: root
  password:

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  database: dynamicmodel_dev
  username: root
  host: localhost
  password: charly

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  host: localhost
  database: dynamicmodel_test
  username: root
  password: charly
